name: ampiy_homepage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cryptofont: ^1.0.2+1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
